apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test
data:
  REDIS_HOST: redis
  ENVIRONMENT: "test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  REDIS_HOST: redis
  ENVIRONMENT: "prod"
