apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: NAMESPACE_PLACEHOLDER
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: NAMESPACE_PLACEHOLDER
spec:
  selector:
    app: counter
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
